apiVersion: apps/v1
kind: Deployment
metadata:
  name: appadi-add-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appadi-add-tasks-api
  template:
    metadata:
      labels:
        app: appadi-add-tasks-api
    spec:
      containers:
      - name: appadi-add-tasks-api
        image: devopsinsidersacr235.azurecr.io/appadi-add-tasks-api:v1
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-dev-appadi.database.windows.net,1433;Database=sqldb-dev-appadi;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"        
