apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appadi-add-tasks-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: add-task-api.innervoicebyaditi.online
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: appadi-add-tasks-api
                port:
                  number: 80
